name: Final Assessment CI/CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: tiny-health-app

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Tests
        run: python -m unittest discover -s tests -v

      - name: Run Trivy Scan (Filesystem)
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: fs
          scan-ref: .
          exit-code: "0"
          severity: "CRITICAL,HIGH"

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Generate Tag
        id: tag
        run: |
          set -e
          TAG="$(date +%F)-${GITHUB_RUN_ID}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated TAG: $TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          set -e

          TAG="${{ steps.tag.outputs.tag }}"
          USER="$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '[:space:]')"

          IMAGE="${USER}/${{ env.IMAGE_NAME }}:${TAG}"

          echo "Building: $IMAGE"

          docker build --pull -t "$IMAGE" .
      - name: Push Image
        run: |
          set -e

          TAG="${{ steps.tag.outputs.tag }}"
          USER="$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '[:space:]')"

          IMAGE="${USER}/${{ env.IMAGE_NAME }}:${TAG}"

          echo "Pushing: $IMAGE"

          docker push "$IMAGE"

      - name: Deploy Container
        run: |
          set -e

          TAG="${{ steps.tag.outputs.tag }}"
          USER="$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '[:space:]')"

          IMAGE="${USER}/${{ env.IMAGE_NAME }}:${TAG}"

          docker stop tiny-app || true
          docker rm tiny-app || true

          docker run -d \
            --name tiny-app \
            -p 8000:8000 \
            -e APP_VERSION="$TAG" \
            -e ENVIRONMENT=production \
            "$IMAGE"

      - name: Validate Deployment
        run: |
          set -e
          sleep 10

          curl --fail http://localhost:8000/health
          curl --fail http://localhost:8000/version
          curl --fail http://localhost:8000/status